# Generated by Django 3.2.5 on 2021-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Прибор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замера')),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Замеры',
                'ordering': ['title'],
            },
        ),
    ]
